version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_HOST: ${TEST_DB_HOST}
      POSTGRES_PORT: ${TEST_DB_PORT}
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - 7052:5432