version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fanisi
    ports:
      - 7001:5432